version : "3.8"

networks:
  services_network:
    name: services_network
  default:
    name: default_network
    
services:
  mongodb:
    image: mongo:latest
    user: root 
    volumes:
      - ./mongo_volume:/data/db
      - ./mongo_volume/logs:/var/logs/mongodb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongodb_container
    restart : always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_DATABASE=tokens
    networks:
      - services_network


  mongo_express:
    image: mongo-express:latest
    container_name : mongo_express
    restart : always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - services_network

volumes:
  microservices_mongo_volume:
    driver: local
